language: node_js
node_js:
  - node

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_script:
  - npm install -g ionic
  - npm install

script:
  - npm run ion
  - npm run test

